### ISSUE TITLE
Issue about identifying terminus regions and ice-dammed lakes

### ISSUE THREAD

**Issue by whyjz** [GLIMS-RGI/lake_terminating#4]
Hello team,

 

Will (@willkochtitzky) and I found something that might be worth a broad discussion when we were validating each other's classification results.

For the lake-terminating boundaries, we want to focus on just the terminus region, not the entire glacier edges. But what defines the terminus region, and how should we separate it from all glacier edges as the first step of the workflow? 

If we follow [Cogley et al.](https://wgms.ch/downloads/Cogley_etal_2011.pdf)'s (2011) definition of a terminus as the "lowest end of a glacier", then we probably need to identify the terminus using some DEMs, but we do not adopt this method based on my understanding of the classification guidelines. Since we are asked to identify the terminus region before classifying the terminus type, I think most of us (if not all) practically use either of both of the strategies listed here:

1. Identify the low end of the glacier (based on topography viewed from the satellite images, not DEMs, as well as the melting status of the glacier) and set up a threshold, e.g. the lowest 100 m or so, as the terminus region. 
2. Track the flow morphology in the satellite images and assign the place where the ice eventually flows to as the terminus region. 

Whichever strategy we use, I think each of us will have a different size of the terminus region when we look at the same glacier. I primarily use the second method, which means multiple, scattered terminus regions can be identified for some glaciers. If any one of them is lake-terminated, I count that for assigning the lake-terminating level. However, for another person who uses the first method, the terminus region may be constrained to a small zone, so the classification is more strict because fewer lakes are viewed as the ending points of the glacier compared to my method. Here are some examples:

![Screenshot from 2024-04-12 13-41-40](https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/8c64feb8-a9a2-4df6-bf19-00e4bb350606)
This glacier splits into two branches, with the right seemingly at a lower elevation (green dot) than the left. The left branch is lake-terminating, and the right branch is ambiguous, depending on how big you assign the terminus zone. Red circles are the lakes that I counted while assigning the lake-terminating levels.

![Screenshot from 2024-04-12 13-46-40](https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/9d86c04e-fd81-4bb0-8720-cfedaab78ef7)
These two lakes can be either close to or within the terminus zone.

![Screenshot from 2024-04-12 14-00-37](https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/102bb11a-1501-4204-b033-17b879a61758)
The right branch is seemingly at a lower elevation than the left branch (green dot). It's partially lake-terminating, but the bigger terminus at the left is not. 

![Screenshot from 2024-04-12 14-31-57](https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/f6ab35ee-e5c8-4d81-b581-a40c1c125643)
A minor end of flow is located in the lower left of the image, where you can find a lake and some calving processes (red circle in the lower left). I counted this as a (non-classical) terminus zone that touches a lake, although it's higher in elevation and smaller than the two major termini (green dots). Some of us might treat this zone differently and not consider the lake while assigning the lake-terminating level.

![Screenshot from 2024-04-12 14-54-59](https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/aed3a064-b413-4b38-8da0-fa2f0098dbf0)
The lake labeled by a red circle (not the red triangle) lies on a topographical low with a stream connected to a proglacial lake nearby. It is some distance away from the main terminus, which may cause a discrepancy on whether to include this area as a terminus zone.

![Screenshot from 2024-04-12 15-17-58](https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/dd1949c5-8afc-4941-af33-e2253765620e)
This is where RGI does not do a good job of splitting the glacier outlines. I'd give the small glacier on the right a level-2 or 3 and the big glacier on the right level-0, but when they are not separated, we can only assign one number here. Again, our method of identifying the terminus regions can affect our level assignment.

![Screenshot from 2024-04-12 15-25-41](https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/46da7f28-12b0-4ce0-be3b-1a6118590875)
The main terminus at the lowest point is land-terminating, but you can see some branches higher up end in lakes.

I think a 3-level classification system has the advantage that we can include as many ambiguities as possible. So with this design, maybe we should look up all "terminus regions" based on the flow morphology instead of the perceived elevations? For me, Example 6 on the project Github page also expresses the same idea. Plus, if our explanation for level-2 and 3 is "lake is probably/possibly relevant for glacier behavior" and we see calving features on those side-ending termini, we can justify our classification and include those glaciers with lake-terminating labels even if the main terminus is purely land-terminating.

Any thoughts are much appreciated!

**Comment by armstrwa** [comment]
Hi Whyjay,

How I've been thinking about this is that we're flagging "lake-terminating
glaciers" not just "glaciers with a lake somewhere along their margin".
What has helped me is thinking about where water from the lake will go - if
it is near the terminus and drains away from the glacier, I would probably
consider relevant to the glacier being lake-terminating or not. If water
from the lake drains under the glacier, then it's an ice-dammed lake and I
have generally not been considering the associated glaciers as
lake-terminating unless: 1) there is evidence for significant flow of ice
into the lake (warped flowlines/fabrics), 2) the lake is large relative to
the glacier's width, and 3) it is located very near the terminus, such that
future retreat will make it a proglacial lake that drains away from rather
than underneath the glacier. I've generally been flagging them as
lake_level = 3 and noting it's an ice-dammed lake in the comments.

I give my take on your example images in-line below, just to give a 2nd
opinion and perhaps work to build some consensus on what we are/aren't
calling lake-terminating.


On Thu, Apr 25, 2024 at 1:26 AM Whyjay Zheng ***@***.***>
wrote:

> Hello team,
>
> Will and I found something that might be worth a broad discussion when we
> were validating each other's classification results.
>
> For the lake-terminating boundaries, we want to focus on just the terminus
> region, not the entire glacier edges. But what defines the terminus region,
> and how should we separate it from all glacier edges as the first step of
> the workflow?
>
> If we follow Cogley et al.
> <https://wgms.ch/downloads/Cogley_etal_2011.pdf>'s (2011) definition of a
> terminus as the "lowest end of a glacier", then we probably need to
> identify the terminus using some DEMs, but we do not adopt this method
> based on my understanding of the classification guidelines. Since we are
> asked to identify the terminus region before classifying the terminus type,
> I think most of us (if not all) practically use either of both of the
> strategies listed here:
>
>    1. Identify the low end of the glacier (based on topography viewed
>    from the satellite images, not DEMs, as well as the melting status of the
>    glacier) and set up a threshold, e.g. the lowest 100 m or so, as the
>    terminus region.
>    2. Track the flow morphology in the satellite images and assign the
>    place where the ice eventually flows to as the terminus region.
>
> Whichever strategy we use, I think each of us will have a different size
> of the terminus region when we look at the same glacier. I primarily use
> the second method, which means multiple, scattered terminus regions can be
> identified for some glaciers. If any one of them is lake-terminated, I
> count that for assigning the lake-terminating level. However, for another
> person who uses the first method, the terminus region may be constrained to
> a small zone, so the classification is more strict because fewer lakes are
> viewed as the ending points of the glacier compared to my method. Here are
> some examples:
>
> Screenshot.from.2024-04-12.13-41-40.png (view on web)
> <https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/8c64feb8-a9a2-4df6-bf19-00e4bb350606>
> This glacier splits into two branches, with the right seemingly at a lower
> elevation (green dot) than the left. The left branch is lake-terminating,
> and the right branch is ambiguous, depending on how big you assign the
> terminus zone. Red circles are the lakes that I counted while assigning the
> lake-terminating levels.
>

I am honestly having trouble interpreting what this image is showing
without more spatial context. I'll abstain on this one.


> Screenshot.from.2024-04-12.13-46-40.png (view on web)
> <https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/9d86c04e-fd81-4bb0-8720-cfedaab78ef7>
> These two lakes can be either close to or within the terminus zone.
>

I wouldn't call either of these lake terminating - they are both ice-dammed
and away from the arcuate region of the terminus. I'd maybe do lake_level =
3 for the eastern glacier b/c icebergs are visible.


> Screenshot.from.2024-04-12.14-00-37.png (view on web)
> <https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/102bb11a-1501-4204-b033-17b879a61758>
> The right branch is seemingly at a lower elevation than the left branch
> (green dot). It's partially lake-terminating, but the bigger terminus at
> the left is not.
>

I'm also having a hard time interpreting this image - sorry.


> Screenshot.from.2024-04-12.14-31-57.png (view on web)
> <https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/f6ab35ee-e5c8-4d81-b581-a40c1c125643>
> A minor end of flow is located in the lower left of the image, where you
> can find a lake and some calving processes (red circle in the lower left).
> I counted this as a (non-classical) terminus zone that touches a lake,
> although it's higher in elevation and smaller than the two major termini
> (green dots). Some of us might treat this zone differently and not consider
> the lake while assigning the lake-terminating level.
>

I would again call this lake_level = 3 but not true "lake-terminating
glacier". Lake is ice-dammed and away from arcuate terminal region.

Screenshot.from.2024-04-12.14-54-59.png (view on web)
> <https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/aed3a064-b413-4b38-8da0-fa2f0098dbf0>
> The lake labeled by a red circle (not the red triangle) lies on a
> topographical low with a stream connected to a proglacial lake nearby. It
> is some distance away from the main terminus, which may cause a discrepancy
> on whether to include this area as a terminus zone.
>

I would give this lake_level = 0. It is far from the true terminus (lowest
point) and very small.

Screenshot.from.2024-04-12.15-17-58.png (view on web)
> <https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/dd1949c5-8afc-4941-af33-e2253765620e>
> This is where RGI does not do a good job of splitting the glacier
> outlines. I'd give the small glacier on the right a level-2 or 3 and the
> big glacier on the right level-0, but when they are not separated, we can
> only assign one number here. Again, our method of identifying the terminus
> regions can affect our level assignment.
>

I have been adding an "RGI issue - should have multiple termini" in the
comment field for these kind of cases. I haven't seen tons of cases like
this (glaciers that should have separate outlines), but I've been giving
lake_level classifications based off the lake-terminating terminus when it
does occur. I would probably give that glacier lake_level = 3 based off the
eastern lobe.


> Screenshot.from.2024-04-12.15-25-41.png (view on web)
> <https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/46da7f28-12b0-4ce0-be3b-1a6118590875>
> The main terminus at the lowest point is land-terminating, but you can see
> some branches higher up end in lakes.
>

I would refer to the trunk glacier in this case and give lake_level = 0.


> I think a 3-level classification system has the advantage that we can
> include as many ambiguities as possible. So with this design, maybe we
> should look up all "terminus regions" based on the flow morphology instead
> of the perceived elevations? For me, Example 6 on the project Github page
> also expresses the same idea Plus, if our explanation for level-2 and 3 is
> "lake is probably/possibly relevant for glacier behavior" and we see
> calving features on those side-ending termini, we can justify our
> classification and include those glaciers with lake-terminating labels even
> if the main terminus is purely land-terminating.
>

I have been trying to keep ice-dammed lakes out of this for simplicity, but
Tobias wanted that Example 6 in there based off his knowledge of the site.
I personally think having ice-dammed lakes makes this really confusing,
will dramatically up the number of lake-terminating glaciers, and makes the
determination more subjective/ambiguous. To me it seems more
straightforward & meaningful to try to just include lakes ther terminate in
proglacial lakes (lakes with water that drains away from terminus).

 I hope those thoughts are useful and don't just add more confusion..

Billy

Any thoughts are much appreciated!

**Comment by willkochtitzky** [comment]
Well said Billy! I agree
I prefer method 1 in Whyjay's post, but very happy to hear other opinions too.

**Comment by whyjz** [comment]
Thanks, @armstrwa! We are definitely not mapping "glaciers with a lake somewhere along their margin," which has made me think about whether we should focus on separating the terminus regions from the margin first. It makes sense to me that we might have the third method—that is, identifying proglacial lakes that drain away from the glacier rather than underneath it. However, the three exceptions you mentioned are still ambiguous to me as "significant flow of ice," "being relatively large," and "being near the terminus" still rely on human judgments.

A good thing is that most ambiguity takes place while classifying level-3 glaciers. We all agree that ice-dammed lakes should not weigh in too much on determining the lake-terminating levels. Here's a table showing our classification of the glaciers from my last post so you can see a certain level of agreement:
 
| Image order  | Whyjay's classification | Will's classification | Billy's classification |
| ------------- | ------------- | ------------- | ------------- |
| 1  | 3  | 0  | --  |
| 2  | 3 & 3  | 0 & 0  | 0 & 3  |
| 3  | 3  | 0  | --  |
| 4  | 3  | 0  | 3  |
| 5  | 3  | 0  | 0  |
| 6  | 2 or 3 | 0 or 3  | 3  |
| 7  | 3  | 0  | 0  |

So I tried to lay out the core question reflecting on these different classifications as follows. If we state, "Knowledge about the existence of lakes which are in contact with glaciers is a fundamental importance to understand as the lakes increase glacier mass loss due to calving, dynamic thinning and increased mass loss at the ice-water interface," and **we see those dynamic signals from ice-dammed lakes (with varying size and distance to the lowest point of the glaciers), to what extent should we include them as level-3?** At first, I was on the aggressive side because I did not want to miss out on any glaciers with dynamic signals due to adjacent water bodies. So before finalizing our classification, I'd love to know what "comfort level" you are at about letting this signal go.

There are a lot of ice-dammed lakes in Arctic Canada North, so this is not a trivial work. Here's an additional figure to show this:

![ice-dammed_lakes](https://github.com/GLIMS-RGI/lake_terminating/assets/19339926/bb2bad83-9c60-4047-ab58-10415aae4828)

If you want to check out these on Google Earth, the left is at (81.624304, -74.314042), and the right is at (81.481148, -85.368415). Both glaciers are land-terminating at their lowest elevations and have an ice-dammed lake ~3 km away from the terminus, showing signs of calving. We have reviewed the case on the left, with two votes for level 0 and one for level 3. For the case on the right, it feels not so reasonable to me to exclude this from the list of lake-terminating glaciers probably because of the long water-ice boundary and many floating icebergs. However, both cases have a similar geometry setting, so we might need some solid justifications for ice-dammed lakes if we want to assign the right one with level-1, -2, or -3 (depending on where you set the margin as the terminus and its length) while keeping the left one level-0 (or level-3 perhaps?).

**Comment by willkochtitzky** [comment]
@whyjz Do you have a clear path forward here? What do we need to do to be able to finish RGI region 3?

**Comment by fidelsteiner** [comment]
Very sorry I dropped this, agree important to have the discussion. Admittedly pretty much irrelevant in the Alps, does appear on the Tibetan Plateau at times (probably more often in future), and of course Greenland. For both examples shown above I actually would have gone for 3. I agree they could play an important role for dynamics and we actually have a whole project just looking at the role such lakes play for ice dynamics. Also knowing that we have relatively few 1 to 3 anyway, I would rather keep them in such a bin to have the chance to rediscuss once have everything compiled. I am also sometimes not sure if they are ice-dammed (i.e. woud run off if the ice dam wasn't there) or are just sitting there anyway.

As for the 'terminus identification', I also follow (1), again knowing this is at times a bit subjective, and for multiple termini went for 3 if the lake is only at the 'lesser/smaller' one. I hope that helps. I think it makes a lot of sense to keep this discussion as part of an essential aspect of the Discussion for the paper, if one ever comes out of it, as it won't be 100% resolved I guess.

**Comment by whyjz** [comment]
Thank you @fidelsteiner for the thoughts! I also prefer that we have a bin (level 3 maybe) for complicated cases and a chance for rediscussion. So based on the ensemble thoughts of four people involved in this thread, how about this strategy:

1. We use method (1) for terminus identification based on the contributor's best judgment and follow the original criteria for the proglacial lakes that touch the terminus. The extra criteria listed here (2. to 4.) are only considered when the terminus is land-terminating.
2. For ice-dammed and other proglacial lakes that are not within the terminus zone, when we see a strong influence of water-induced glacier dynamics (e.g., calving, icebergs,...) that would be assigned as level 2 or above if it were in the terminus zone, we assign the glacier level 3. 
3. (Same context from 2.) If we see the water-induced glacier dynamics but not strong enough to be classified as level 3, we use lake_level = 9. (unclassified).
4. (Same context from 2.) If we don't see any water-induced glacier dynamics, we use lake_level = 0.

Always happy to discuss it further. Canadian Arctic is indeed a special region in terms of proglacial lakes.

**Comment by fidelsteiner** [comment]
sounds good to me to move ahead like that yes. i think not just for this issue we will anyway need to huddle together to revisit unclear cases at the very end of the compilation round.

**Comment by fidelsteiner** [comment]
sounds good to me to move ahead like that yes. i think not just for this issue we will anyway need to huddle together to revisit unclear cases at the very end of the compilation round.

**Comment by willkochtitzky** [comment]
Sounds good to me, thanks for working on this Whyjay!

**Comment by willkochtitzky** [comment]
@whyjz, looking at your files now, I didnt fully grasp point 3 that you wrote above about assigning things #9. I think this is problematic and we really need every glacier to have a classification. I think that all the 9s you are classifying should be land terminating.

**Comment by whyjz** [comment]
@willkochtitzky, are you referring to all class-9 glaciers or some of them that are classified based on point 3 above? There were no satellite images in the northern North Ellesmere Ice Cap around the year 2000, so I put many 9's there.

**Comment by willkochtitzky** [comment]
Hi Whyjay, good point, I had forgotten about the Northern Ellesmere glaciers. I think we really need a term type every glacier. Even if it is our best effort. I can help with those, I have some imagery from ASTER I could use.
If we have to use more modern imagery (like ESRI base layers) that is fine. It is most important that we are complete with our best guess, in my opinion.
But in my comment above I was specifically referring to point 3 - I think these glaciers should be land terminating, not unclassified.

**Comment by whyjz** [comment]
Oh, I didn't catch that since we said "*When in doubt whether the glacier is in contact with a lake or not, use level 3; if it seems more likely that the glacier is not in contact but you cannot verify from the utilized image or any other image source (e.g. because of clouds, snow cover, cast shadow), use the "not assigned" category (term_type=9)*" in the README file of this repository.

I can update the North Ellesmere with my best guess if you don't mind the reference images (or ESRI/Google basemaps) deviating much away from 2000. (And if we do this, I think it's necessary to let the whole team know since in README it says "*If an inventory is lacking or too far removed in time from 2000 (>10 years away) the classification is done manually based on satellite imagery from 2000. If neither of these approaches are taken, all glaciers in that region are flagged as ‘not assigned’ terminus type (term_type = 9).*)

For the class-9 glaciers due to point 3, I am okay with them reclassifyed as 0.

**Comment by willkochtitzky** [comment]
@whyjz we can ask others, I strongly believe that a classification from any date is better than no classification. Ideally, yes we have a date associated with it as close to 2000 as possible. In that text Billy is referring to published inventories, which don't exist for this region. I know ASTER imagery exists for ACN, but it is on my work computer and I am at home right now, but I can look at it.

If there are mistakes in the marine classification, I think we should try to fix those here. That is my inventory for marine-terminating glaciers, happy to edit it.

**Comment by armstrwa** [comment]
Whyjay & Will - It seems to me that if you’re seeing misclassified
marine-terminating glaciers, you could directly modify the term_type field
rather than lake_level. We will have to have some kind of script that
reconciles old RGI term type classifications with our new flags (based on
lake level) and it seems like it would be straight forward to add a few
lines to check for cases marine term type in the old classification changed
to lake or land in the new classification.

Does that make sense to you guys? It just seems good to be clear about your
process (which you’re already doing) and ideally to be consistent across
contributors who are running into similar issues (so it’s helpful to be
having the discussion here) so we can correctly handle them down the line.

Billy

--------------------------------------------------------
Dr William Armstrong (he/him)
Assistant Professor
Geological and Environmental Sciences
Appalachian State University

email: ***@***.***
web: https://sites.google.com/appstate.edu/warmstrong/
phone: 828-262-6739
office: Rankin Science West, Room W041
mail: ASU Box 32067, Boone, NC 28608
--------------------------------------------------------

**Comment by willkochtitzky** [comment]
@armstrwa agreed!

**Comment by fmaussion** [comment]
Yes - while RGI 7.1 wont change the outlines, there is still possibility to change the attributes.

**Comment by whyjz** [comment]
Hi all, sounds good. I have just reclassified all class-9 glaciers. To make the changes stand out for later workflows, I am now using different values for `lake_terminating_level` instead of changing the `term_type` values:

- `lake_terminating_level=99`: glaciers ending in ocean water, landfast ice, or ice shelf (northern Ellesmere island only)
- `lake_terminating_level=0`: glaciers ending on land, converging into another glacier, or (for very small glaciers) invisible/unclear glacier outlines

Once we figure out a way to include these extra marine-terminating glaciers, we can change all the class-99 glaciers into something more suitable.

**Comment by iamdonovan** [comment]
@armstrwa - my plan for updating the `term_type` attribute is similar to [these lines](https://github.com/GLIMS-RGI/lake_terminating/blob/7a6e729d750d9979444f7df32f13f1f866b5ba58/scripts/assign_lake_flag.py#L74): only update the `term_type` attribute if it is currently set to `9`; otherwise, leave it as-is.
